server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arlymiguel/repository_general.git
          username: arly.miguel.fernandez@gmail.com
          password: Seguros201802
          
endpoints:
  sensitive: true
  
management:
  security:
    enable: false